#!/bin/bash
# /etc/init.d/mcramdisk
# version 1.0.0 2011-11-07 (YYYY-MM-DD)

### BEGIN INIT INFO
# Provides:   minecraft_ramdisk
# Required-Start: $local_fs $remote_fs
# Required-Stop:  $local_fs $remote_fs
# Should-Start:   
# Should-Stop:    
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description:    Ramdisk for Minecraft
# Description:    Makes a Ramdisk for a Minecraft server
### END INIT INFO

#Variables
USERNAME="minecraft"
RD_PATH='/mnt/codecraft/ramdisk'
RD_SIZE='256M'

#Force all commands to be run as $USERNAME
ME=`whoami`
as_user() {
  if [ $ME == $USERNAME ] ; then
    bash -c "$1"
  else
    su - $USERNAME -c "$1"
  fi

# Mount the Ramdisk at $RD_PATH
mcrd_start() {
  if mount -l -t tmpfs | grep $RD_PATH > /dev/null
  then 
    echo "Ramdisk already mounted"
  else
    echo "Mounting Ramdisk at $RD_PATH"
    as_user "mount -t tmpfs -o size=$RD_SIZE tmpfs $RD_PATH"
    sleep 3
    if mount -l -t tmpfs | grep $RD_PATH > /dev/null
    then 
      echo "Ramdisk mounted at $RD_PATH"
    else
      echo "Could not mount Ramdisk. Does $RD_PATH exist?"
    fi
  fi
}

# Unmount the ramdisk
mcrd_stop() {
  if mount -l -t tmpfs | grep $RD_PATH > /dev/null
  then
    echo "Ramdisk mounted at $RD_PATH.... unmounting"
    as_user "umount $RD_PATH"
    sleep 3
  else
    echo "Ramdisk was not mounted at $RD_PATH"
  fi
  
  if mount -l -t tmpfs | grep $RD_PATH > /dev/null
  then
    echo "Could not unmount ramdisk at $RD_PATH"
  else
    echo "Ramdisk unmounted"
  fi
}

# Commands
case "$1" in
  mount)
    mc_start
    ;;
  umount)
    mc_stop
    ;;
  reset)
    mc_stop
    mc_start
    ;;
  status)
    if mount -l -t tmpfs | grep $RD_PATH > /dev/null
    then
      echo "Ramdisk mounted at $RD_PATH"
    else
      echo "Ramdisk is not mounted"
    fi
    ;;
    *)
  echo "Usage: mcramdisk {mount|umount|reset|status}"
  echo "BE CARFUL WITH THE RESET COMMAND. IT WILL UNMOUNT THE RAMDISK"
  exit 1
  ;;
esac

exit 0
