#!/bin/bash
# /etc/init.d/minecraft
# version 0.1.0 2011-11-07 (YYYY-MM-DD)

### BEGIN INIT INFO
# Provides:   minecraft
# Required-Start: $local_fs $remote_fs
# Required-Stop:  $local_fs $remote_fs
# Should-Start:   $network
# Should-Stop:    $network
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description:    Minecraft server
# Description:    Starts the minecraft server
### END INIT INFO

#Settings
SERVICE='craftbukkit.jar'
USERNAME='minecraft'
SCREEN_NAME='codecraft'
BUILD='b1337'
MC_PATH="/mnt/codecraft/servers/$BUILD"
RD_PATH="/mnt/codecraft/ramdisk/$BUILD"
WORLD_PATH='/mnt/codecraft/worlds'
WORLD_BACKUPPATH='/mnt/codecraft/archives/worlds'
SERVER_BACKUPPATH='/mnt/codecraft/archives/servers'
INVOCATION="java -Xms512M -Xmx2048M -jar craftbukkit.jar"
SAVE_OFF_MSG="SERVER BACKUP STARTING. Server going readonly..."
SAVE_ON_MSG="SERVER BACKUP ENDED. Server going read-write..."
STOP_MSG=""

ME=`whoami`
as_user() {
  if [ $ME == $USERNAME ] ; then
    bash -c "$1"
  else
    su - $USERNAME -c "$1"
  fi
}

mc_start() {
  if ps ax | grep -v grep | grep -v -i SCREEN | grep $SERVICE > /dev/null
  then
    echo "Tried to start but $SERVICE was already running!"
  else
    echo "$SERVICE was not running... starting."
    cd $MCPATH
    as_user "cd $MC_PATH && screen -dmS $SCREEN_NAME $INVOCATION"
    sleep 7
    if ps ax | grep -v grep | grep -v -i SCREEN | grep $SERVICE > /dev/null
    then
      echo "$SERVICE is now running."
    else
      echo "Could not start $SERVICE."
    fi
  fi
}

mc_saveoff() {
  if ps ax | grep -v grep | grep -v -i SCREEN | grep $SERVICE > /dev/null
  then
    echo "$SERVICE is running... suspending saves"
    as_user "screen -p 0 -S $SCREEN_NAME -X eval 'stuff \"say $SAVE_OFF_MSG\"\015'"
    as_user "screen -p 0 -S $SCREEN_NAME -X eval 'stuff \"save-off\"\015'"
    as_user "screen -p 0 -S $SCREEN_NAME -X eval 'stuff \"save-all\"\015'"
    sync
    sleep 10
  else
    echo "$SERVICE was not running. Not suspending saves."
  fi
}

mc_saveon() {
  if ps ax | grep -v grep | grep -v -i SCREEN | grep $SERVICE > /dev/null
	then
		echo "$SERVICE is running... re-enabling saves"
    as_user "screen -p 0 -S codecraft -X eval 'stuff \"save-on\"\015'"
    as_user "screen -p 0 -S codecraft -X eval 'stuff \"say $SAVE_ON_MSG\"\015'"
	else
    echo "$SERVICE was not running. Not resuming saves."
	fi
}
